Eta40 = {
    "dias": 9,
    "numero_modelo": 3,
    "nome_arquivo": "ETA40_m_",
    "datanames_sintegre": [
        "Codigo ANA",
        "lat",
        "lon",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
    ],
    "datanames_column": [
        "Bacia",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
    ],
    "datanames_final": [
        "Bacia",
        "modelo",
        "datetoday",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
    ],
}

Gefs50 = {
    "dias": 14,
    "numero_modelo": 2,
    "nome_arquivo": "GEFS_m_",
    "datanames_sintegre": [
        "Codigo ANA",
        "lat",
        "lon",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
    "datanames_column": [
        "Bacia",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
    "datanames_final": [
        "Bacia",
        "modelo",
        "datetoday",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
}

ECMWF = {
    "dias": 14,
    "numero_modelo": 1,
    "nome_arquivo": "ECMWF_m_",
    "datanames_sintegre": [
        "Codigo ANA",
        "lat",
        "lon",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
    "datanames_column": [
        "Bacia",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
    "datanames_final": [
        "Bacia",
        "modelo",
        "datetoday",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
    ],
}
